---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    toolkit.fluxcd.io/tenant: helm-test2
  name: helm-test2
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    toolkit.fluxcd.io/tenant: helm-test2
  name: helm-test2
  namespace: helm-test2
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    toolkit.fluxcd.io/tenant: helm-test2
  name: helm-test2-reconciler
  namespace: helm-test2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: gotk:helm-test2:reconciler
- kind: ServiceAccount
  name: helm-test2
  namespace: helm-test2
