---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: helm-test2
  namespace: helm-test2
spec:
  interval: 1m0s
  url: https://github.com/GitHubforGitLab/flux2-multi-tenancy
  ref:
    branch: helm-test2
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: helm-test2
  namespace: helm-test2
spec:
  interval: 1m0s
  path: ./
  prune: false
  serviceAccountName: helm-test2
  sourceRef:
    kind: GitRepository
    name: helm-test2
