---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: helm-test1
  namespace: helm-test1
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/ClownandBox/flux2-multi-tenancy-helm-test1
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: helm-test1
  namespace: helm-test1
spec:
  interval: 1m0s
  path: ./
  prune: false
  serviceAccountName: helm-test1
  sourceRef:
    kind: GitRepository
    name: helm-test1
